# Generated by Django 5.0.3 on 2024-03-13 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='adsress',
            new_name='address',
        ),
    ]
