# Generated by Django 5.0.3 on 2024-03-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_adsress_userinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='location',
            field=models.CharField(default=1, max_length=255, verbose_name='user location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone_number',
            field=models.CharField(default=1, max_length=25, verbose_name='user phone number'),
            preserve_default=False,
        ),
    ]
