# Generated by Django 5.0.3 on 2024-03-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Testimonialers', verbose_name='Testimonialer image')),
                ('fullname', models.CharField(max_length=255, verbose_name='Testimonialer fullname')),
                ('job', models.CharField(max_length=70, verbose_name='Testimonialer job')),
                ('testimonial', models.TextField(verbose_name='Testimonialer testimonial')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
