# Generated by Django 5.0.3 on 2024-03-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('place', models.CharField(max_length=30, verbose_name='Place')),
                ('year', models.CharField(max_length=255, verbose_name='Year')),
                ('subtitle', models.CharField(max_length=255, verbose_name='SubTitle')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('place', models.CharField(max_length=30, verbose_name='Place')),
                ('year', models.CharField(max_length=255, verbose_name='Year')),
                ('subtitle', models.CharField(max_length=255, verbose_name='SubTitle')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
