# Generated by Django 5.0.3 on 2024-03-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='image',
            field=models.URLField(verbose_name='Video'),
        ),
    ]
