# Generated by Django 5.0.2 on 2024-03-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': 'User admin', 'verbose_name_plural': 'Users admin'},
        ),
    ]
