# Generated by Django 5.0.2 on 2024-03-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_infouser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='description',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='image',
            field=models.ImageField(default=1, upload_to='InfoUser', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='instagram',
            field=models.URLField(default=1, verbose_name='Instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='phone',
            field=models.CharField(default=1, max_length=255, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='telegram',
            field=models.URLField(default=1, verbose_name='Telegram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='whatsapp',
            field=models.URLField(default=1, verbose_name='Whatsapp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='work',
            field=models.CharField(default=1, max_length=255, verbose_name='Job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infouser',
            name='youtube',
            field=models.URLField(default=1, verbose_name='YouTube'),
            preserve_default=False,
        ),
    ]
