# Generated by Django 4.2.7 on 2024-03-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка 1")),
                ("descriptions", models.TextField(verbose_name="Описание")),
                ("image", models.ImageField(upload_to="settings", verbose_name="Фото")),
                (
                    "title2",
                    models.CharField(max_length=155, verbose_name="Заголовка 2"),
                ),
                ("descriptions2", models.TextField(verbose_name="Описание 2")),
                (
                    "title3",
                    models.CharField(max_length=155, verbose_name="Заголовка 3"),
                ),
                ("descriptions3", models.TextField(verbose_name="Описание 3")),
                (
                    "title4",
                    models.CharField(max_length=155, verbose_name="Заголовка 4"),
                ),
                ("descriptions4", models.TextField(verbose_name="Описание 4")),
            ],
            options={
                "verbose_name_plural": "Настройки всего страницы",
            },
        ),
    ]
